title: Antonio Ribeiro
logo: Assets/am1r.jpg
description: >
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"><br>
  <a href="mailto:antonio.ribeiro0516@gmail.com">
    <i class="fas fa-envelope"></i> antonio.ribeiro0516@gmail.com
  </a><br>
  <a href="tel:+27682167936">
    <i class="fas fa-phone"></i> +27 68 216 7936
  </a><br>
  <a href="https://www.linkedin.com/in/antonio-ribeiro-b212382a6/" target="_blank">
    <i class="fab fa-linkedin-in"></i> LinkedIn Profile
  </a><br><br>


  
  I'm Antonio Ribeiro, an aspiring Data Scientist enrolled in the ALX Data Science program. I have a strong foundation in data analytics, Python, and machine learning, combined with practical experience in legal and warehouse administration. Skilled in data organization, reporting, and tools like Oracle and Excel, I’m motivated to leverage my skills to solve real-world problems and deliver actionable insights.


show_downloads: false
theme: jekyll-theme-minimal
