title: Antonio Ribeiro
description: >
  Aspiring Data Scientist enrolled in the ALX Data Science program. Experienced in data analytics, Python, machine learning, legal & warehouse admin, Oracle & Excel.

email: antonio.ribeiro0516@gmail.com
phone: "+27 68 216 7936"
linkedin: https://www.linkedin.com/in/antonio-ribeiro-b212382a6/

theme: minimal-mistakes-jekyll

# Homepage sections order
homepage_sections:
  - about
  - video
  - portfolio
  - contact

author:
  name: Antonio Ribeiro
  email: antonio.ribeiro0516@gmail.com
  phone: "+27 68 216 7936"
  linkedin: https://www.linkedin.com/in/antonio-ribeiro-b212382a6/

social:
  email: antonio.ribeiro0516@gmail.com
  linkedin: https://www.linkedin.com/in/antonio-ribeiro-b212382a6/

show_downloads: false

