title: Antonio Ribeiro
#logo: 
description: Antonio.ribeiro0516@gmail.com 
description: 0682167936
description: LinkedIn - https://www.linkedin.com/in/antonio-ribeiro-b212382a6/
description: I'm Antonio Ribeiro, an aspiring Data Scientist enrolled in the ALX Data Science program. I have a strong foundation in data analytics, Python, and machine learning, combined with practical experience in legal and warehouse administration. Skilled in data organization, reporting, and tools like Oracle and Excel, I’m motivated to leverage my skills to solve real-world problems and deliver actionable insights.
Show_downloads: false
theme: jekyll-theme-minimal
